[build]
  publish = "."
  functions = "functions"

[functions]
  node_bundler = "esbuild"
  included_files = [
    "functions/benaks-logo.png",
    "functions/OpenSans-Regular.ttf" # <--- TTF included
  ]

[dev]
  functions = "functions"
  publish = "."
